### ISSUE TITLE
Tipografia

### ISSUE THREAD

**Issue by ldenardin** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero#12]

**Comment by LeandroAugustoSantos** [comment]
A fonte escolhida foi Urbanist, fonte simples e elegante para facilitar a leitura e a harmonização do projeto.



![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero/assets/143044412/b359d3c0-8981-4c5a-a4fb-198ad6fc5304)
