### ISSUE TITLE
Iconografia

### ISSUE THREAD

**Issue by ldenardin** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero#14]

**Comment by LeandroAugustoSantos** [comment]
Os ícones foram escolhido com base na harmonização do site, abaixo o significado de cada ícone do projeto.

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero/assets/143044412/b07f0caa-3124-4ec6-bbea-3c9e093902a1)
