### ISSUE TITLE
Template Padrão

### ISSUE THREAD

**Issue by HgBertani** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero#18]

**Comment by LeandroAugustoSantos** [comment]
O design foi pensado para proporciona uma visualização harmônica para o usuário. Abaixo o layout nas versões Desktop e Mobile, a tela inicial do projeto terá esse formato, mostrando a logo, ícone do perfil do usuário e os prestadores de serviço.

DESKTOP

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero/assets/143044412/2cc725e4-e34d-467e-beb7-ca3b5bd6286e)

MOBILE



![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-house-hero/assets/143044412/8b1bfe58-a280-4ce1-9c3e-57cff015dccf)
